version: 0.1.{build}
image: Ubuntu1804
platform: x64
clone_depth: 1
branches:
  only:
  # Release tags
  - /^v\d+\.\d+\.\d+.*$/
  - master
  - develop

environment:
  PATH: /home/appveyor/.rvm/gems/ruby-2.0.0-p648/bin:/home/appveyor/.rvm/gems/ruby-2.0.0-p648@global/bin:/home/appveyor/.rvm/rubies/ruby-2.0.0-p648/bin:/usr/lib/jvm/java-9-openjdk-amd64/bin:/home/appveyor/.gvm/bin:/home/appveyor/.gvm/bin:/home/appveyor/.nvm/versions/node/v4.9.1/bin:/opt/appveyor/build-agent:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/appveyor/.dotnet/tools:/home/appveyor/.rvm/bin:/home/appveyor/.rvm/bin:/opt/mssql-tools/bin:/home/appveyor/.cargo/bin
  UPLOAD_TOKEN:
    secure: 8GZ0hTW+Z5v2qPUgsqFehWQ+osbocNYWRQybTihov35i7QCi+aiRDCI4Xl7ULOszCZzHCFNcL364TxpaCloiOhHCtQEsN3BwypfRll8Q6Ck=

cache:
- /home/appveyor/.cargo
- /home/appveyor/projects/simplebot/target

install:
- sh: curl https://sh.rustup.rs -sSf | sh -s -- -y
- rustc -Vv
- cargo -V

build_script:
- cargo check
- cargo build --release

test_script:
- cargo test

deploy_script:
- ps: >-
    if(${env:UPLOAD_TOKEN}) {
      cd /home/appveyor/projects/simplebot/target/release/
      Compress-Archive -Path ./simple-bot -DestinationPath SimpleBot.zip
      Invoke-RestMethod -Uri "https://splamy.de/api/nightly/simplebot/${env:APPVEYOR_REPO_BRANCH}_linux?token=${env:UPLOAD_TOKEN}&filename=SimpleBot.zip&commit=${env:APPVEYOR_REPO_COMMIT}&version=0.1.0" -Headers @{ "Content-Type" = "application/zip" } -Method Put -InFile ./SimpleBot.zip
    }
